travis:
  secure:
    BINSTAR_TOKEN: fFaM/PMWfB+oe2epN1oybX1AyQOTZ/O7vkjCCpW8y7q+PwrN2V0m3BSxawn07Zr4lsFjjZvBDObGUyszvAj3rsGBet0zEQd2eiTUQeI4kHg3psKoHAboivMezRftcxViX/RcwJgRh4ovJzizHHia0mg0R2f8HtNtb89MnisLimdws8I6LRJ2uD2iqwK6ib2KM0pa1/VU/FXjoBinAOiEMw2+1MBZV5j5WnwBIqIBz40T03CG3NqK77GgecKmQZfzHomlfT2PAOQeEaQeMrxTDdwXigJbi5OVzM5QKWsp76nsWN9I+TBlHobwMo1haByCa/DtniVYXaFOYNh5AajV3xuFUMFOoMQWStTIhgQORr/FotmCmsx+G0fV00Uuf/VpjyahcYh64Th1XwD5idQARGCP744ffpQk/rIDhW4msJHiwxzbcgrzy65zXB20u6CXgYPpyizjWRXwUI7o70uWmTvZK/Tk0eCAhpgtgiVG6eBnlPMrknclvKu58AnHjIE+qc/LiUqouZseDxb0BlAltjdq/ba7YV/8nm0xGBgu/0Z4LmpFKNmLjb939dSPuv1MXa9MFMWAOgnuzS/swxXPvWsTXZFoJiXTLBE/k0ygJqR2CNavgVa88hi+1a2CNwNih3hPhs5mK1pkbWKqKlNCp+xhdoRjXQh4SJ9brnsrf8c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
